engines:
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
  csslint:
    enabled: false
